spring:
  application:
    name: probe
  profiles:
    active: dev
  quartz:
    job-store-type: memory
server:
  port: 8081
  servlet:
    context-path: /probe
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mf.probe.model
logging:
  level:
    root: info
  file:
    name: logs/probe.log
probe:
  id: 1
  customer-id: 1
  tasks-thread-pool:
    core: 5
    max: 10
    keep-alive-time: 10
    queue-size: 20
