spring:
  application:
    name: server
  profiles:
    active: dev

server:
  port: 8082
  servlet:
    context-path: /server
logging:
  level:
    root: info
  file:
    name: logs/server.log
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mf.server.model
