spring:
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/server?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 1
    listener:
      ack-mode: manual_immediate
      missing-topics-fatal: false
    consumer:
      isolation-level: read_committed
      group-id: server-consumer-group
      fetch-max-wait: 4000
#      enable-auto-commit: true

server:
  port: 8082
  servlet:
    context-path: /server
logging:
  level:
    root: info
  file:
    name: logs/server.log
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mf.server.model
