spring:
  application:
    name: server
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 1
    listener:
      ack-mode: manual_immediate
      missing-topics-fatal: false
    consumer:
      isolation-level: read_committed
      group-id: test-consumer-group

server:
  port: 8082
